# Generated by Django 3.2.13 on 2022-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmanager',
            name='linkobj',
            field=models.CharField(default='', max_length=255),
        ),
    ]
