# Generated by Django 3.2.14 on 2022-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_nftitem_nfttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftusers',
            name='nftPhoto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
