# Generated by Django 3.2.14 on 2022-07-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_nftusers_nftphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='nftElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nftElementName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nftRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nftRarityName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nftTypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftCountDown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftDescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mainsite.nftusers'),
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftWatched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nftitem',
            name='nftCreators',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='mainsite.nftusers'),
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftElements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.nftelement'),
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftRarities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.nftrarity'),
        ),
        migrations.AddField(
            model_name='nftitem',
            name='nftTypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.nfttype'),
        ),
    ]
